name: tests

on: ['push']

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker-compose build
        run: docker-compose build
        working-directory: ./tests

      - name: docker-compose up -d ldap api
        run: docker-compose up -d ldap api
        working-directory: ./tests

      - name: docker-compose up --abort-on-container-exit tests
        run: docker-compose up --abort-on-container-exit tests
        working-directory: ./tests
